
# The name of your website.
name: Holo Alfa

description:

  # Discription of your site, this will show up in google.
  meta: Holo Alfa is a minimalist, mobile first Jekyll theme with focus on readability and content. Not ready for primetime yet.

  # Discription of your site, this will show up on the front page.
  subtitle: Holo Alfa is a minimalist, mobile first Jekyll theme with focus on readability and content. Not ready for primetime yet. <a href="https://github.com/steinvc/holo-alfa">&lt;/&gt; on Github</a>.

author:
  name: Stijn van Cuijk

  # Optional text (html) to dislay after author name. Leave empty if you don't
  # want it.
  info: (@<a href="#">twitter-handle</a>)

# The URL of the homepage of your site (without trailing slash).
url: http://steinvc.github.io/holo-alfa


##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: true
display-social-icons: false

footer-text: This is the footer.

# language attribute in <html> element.
lang: en

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 0, 240, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"

# Minimal screen-width after wich the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 3

# Leave empty if you don't want comments on post pages.
disqus-shortname:


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter:
youtube:
instagram:
tumblr:
facebook:
google-plus:
reddit:
soundcloud:
medium:
linkedin:
github:
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Usefull for translating into other languages.

var_on_the_web: On the web
var_read: Read # Text after each post summary on the homepage.
var_newer: Newer
var_older: Older
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: Post by
var_guest_post_by: Guest post by


###############
# OTHER STUFF #
###############

highlighter: pygments
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
