
name: Blank Slate # The name of your website
url: http://steinvc.github.io/blank-slate # The URL of the homepage of your site (without trailing slash).
description: A lightweight, mobile first Jekyll theme. # Discription of your site, this will show up in google and in the header of every page (if subtitle is set to true).

subtitle: false # Set to false if you dan't want a subtitle on your site.
paginate: 3 # Number of posts on each post-page.

lang: nl # language attribute in <html> element

date_format: "%b %-d, %Y" # http://alanwsmith.com/jekyll-liquid-date-formatting-examples

# Customizable text. Usefull for translating into other languages.
footer-text: This is the footer
var_read: Read # text after each post summary on the homepage
var_newer: Newer
var_older: Older
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read # text after reading time

paginate_path: "/page-:num/"
permalink: pretty
defaults:

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
